### ISSUE TITLE
New encoding for SequenceSection

### ISSUE THREAD

**Issue by bookdude13** [teslaworksumn/proton-cli#1]
"Sequence section data is currently encoded as a json array [4, 2, 34, 1, 95]. This is an awful encoding, we should switch to some binary format." - @rjayatilleka

**Comment by computergeek125** [comment]
Additional thoughts: the binary data has to be encoded somehow (a stream of bytes may or may not work).  Idea: encode it as gzip/bzip2/xzip.  Added benefit of smaller file size.

**Comment by bookdude13** [comment]
No longer relevant. Storing stuff in databases
